app/cookie/__init__.py
from flask import Blueprint

cookie_bp = Blueprint("cookie_bp", __name__, "templates/cookie")

app/cookie/views.py
from flask import render_template, request, session, make_response, redirect, url_for, flash
from flask_login import login_required
from . import cookie_bp


@cookie_bp.route("/info", methods=['GET', 'POST'])
@login_required
def info():
    
    #if not session.get("username"):
    #    flash("Please check the box 'remember me'", "danger")
    #    return redirect(url_for('login'))
    
    username = session.get("username")
    cookies = request.cookies
    return render_template("info.html", username=username, cookies=cookies)



@cookie_bp.route('/setCookie', methods=["POST"])
def setCookie():
    key = request.form.get("key")
    value = request.form.get("value")
    days = request.form.get("days")
    #message = "Cookie successfully set"
    response = make_response(redirect(url_for('info')))
    response.set_cookie(key, value, max_age=60*60*24*int(days))
    flash("Cookie set successfully", "success")
    return response


@cookie_bp.route("/deleteCookieByKey", methods=["POST"])
def deleteCookieByKey():
    key = request.form.get("key")
    response = make_response(redirect(url_for('info')))
    response.delete_cookie(key) 
    flash("Cookie deleted by key successfully", "success")
    return response


@cookie_bp.route("/deleteCookieAll", methods=["POST"])
def deleteCookieAll():
    cookiesKeys = request.cookies
    response = make_response(redirect(url_for('info')))
    
    for key, value in cookiesKeys.items():
        if key != "session":
            response.delete_cookie(key)
    flash("Cookie deleted successfully", "success")    
    return response

app/cookie/templates/cookie/info.html
{% from 'fieldMac{% from 'fieldMacro.html' import displayField %}
{% extends 'base.html' %}
{% block title %}Info{% endblock %}
{% block content %}
    <h2 class="mt-50 text-center">Info</h2>
    
    <br><br>

    <div class="container">
        <h4>Welcome <strong>{{ current_user.username }}</strong></h4>

        <!-- Logout button -->
        <div class="d-flex align-items-center justify-content-start">
            <div class="mt-3">
                <form action="{{ url_for('auth.logout') }}" method="POST">
                    <button type="submit" class="btn btn-primary" style="width: 100%;">Logout</button>
                </form>
            </div>
        </div>
        <br><hr>
    </div>

    <!-- Set Cookie -->
    <div class="container mt-50">
        <h4 class="text-center">Set Cookie</h4>
        <div class="container mt-50">
            <div class="d-flex align-items-center justify-content-start">
                <div class="mt-3">
                    <form action="{{ url_for('cookie_bp.setCookie') }}" method="POST">
                        <div class="form-group">
                            <label for="key" class="form-label mt-4">Key</label>
                            <input type="text" class="form-control" id="key" name="key"  placeholder="Key">
                            <label for="value" class="form-label mt-4">Value</label>
                            <input type="text" class="form-control" id="value" name="value" placeholder="Value">
                        </div>
                        <div class="form-group">
                            <label for="days" class="form-label mt-4">Expiry time (in days)</label>
                            <input type="number" class="form-control" id="days" name="days" placeholder="1">                            
                        </div>
                        <br><br>
                        <button type="submit" class="btn btn-primary" style="width: 100%;">Set cookie</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><hr>

    <!-- Delete Cookie -->
    <div class="container mt-50">
        <h4 class="text-center">Delete Cookie</h4>

        <div class="d-flex align-items-center justify-content-start">
            <div class="mt-3">
                <form action="{{ url_for('cookie_bp.deleteCookieByKey') }}" method="POST">
                    <div class="form-group">
                        <label for="key" class="form-label mt-4">Key</label>
                        <input type="text" class="form-control" id="key" name="key"  placeholder="Key" required>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary" style="width: 100%;">Delete by Key</button>
                </form>
                <br>
                <form action="{{ url_for('cookie_bp.deleteCookieAll') }}" method="POST">
                    <button type="submit" class="btn btn-primary" style="width: 100%;">Delete All</button>
                </form>
            </div>
        </div>
    </div>
    <br><hr>

    <!-- Cookies table -->
    <div class="container mt-50">
        <h4 class="text-center">Cookies</h4>
        <table class="table table-hover mt-30">
            <thead>
              <tr>
                <th scope="col">№</th>
                <th scope="col">Key</th>
                <th scope="col">Value</th>
              </tr>
            </thead>
            <tbody>
                {% for key, value in cookies.items() %}
                    <tr class="table-dark">
                        <th scope="row">{{ loop.index }}</th>
                        <td>{{ key }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
    <br><hr>

    <!-- Change password -->
    <div class="container mt-50">
        <a href="{{ url_for('auth.resetPassword') }}">
            <button class="btn btn-primary">Reset password</button>
        </a>
    </div>
    

    <br><br><br><br><br><br><br><br>
{% endblock %}