app/todo/models.py
from app import db

class Todo(db.Model):
    __tablename__ = "todo"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.String(200))
    complete = db.Column(db.Boolean)

app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class AddTodoItemForm(FlaskForm):
    title = StringField("Enter a task here", validators=[DataRequired("This field is required")])
    description = StringField("Enter description here", validators=[DataRequired("This field is required")])
    submit = SubmitField("Save")

app/todo/__init__.py
from flask import Blueprint

todo = Blueprint("todo", __name__, template_folder="templates/todo")

app/todo/views.py
from flask import render_template, redirect, url_for
from .forms import AddTodoItemForm
from .models import Todo
from app import db
from . import todo

@todo.route('/todo', methods=["GET", "POST"])
def todos():
    form = AddTodoItemForm()
    todo_list = Todo.query.all()
    return render_template('todo.html', form=form, todo_list=todo_list)


@todo.route('/todo/add', methods=["POST"])
def add():
    form = AddTodoItemForm()
    
    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        todoItem = Todo(title=title, description=description, complete=False)
        db.session.add(todoItem)
        db.session.commit()
        
    return redirect(url_for("todo.todos"))


@todo.route('/todo/delete/<int:id>')
def delete(id):
    todoItem = Todo.query.filter_by(id=id).first_or_404()
    db.session.delete(todoItem)
    db.session.commit()
    return redirect(url_for('todo.todos'))


@todo.route('/todo/update/<int:id>')
def update(id):
    todoItem = Todo.query.filter_by(id=id).first_or_404()
    todoItem.complete = not todoItem.complete
    db.session.commit()
    return redirect(url_for('todo.todos'))

app/todo/templates/todo/todo.html
{% extends 'base.html' %}
{% block title %}Todo{% endblock %}
{% block content %}
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <h3 class="text-center my-3 pb-3">Your To Do list</h3>
            <br>
            <form class="row" action="{{ url_for('todo.add') }}" method="POST">
              {{ form.hidden_tag() }}
              <div class="col-5">
                <div class="form-outline">
                  {{ form.title(class="form-control", placeholder="Enter a task here") }}
                </div>
              </div>
              <div class="col-5">
                <div class="form-outline">
                  {{ form.description(class="form-control", placeholder="Enter description here") }}
                </div>
              </div>
              <div class="col-2">
                {{ form.submit(class="btn btn-primary") }}
              </div>
            </form>

            <br><br>
            
            <table class="table mb-4">
              <thead>
                  <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                  </tr>
              </thead>
              <tbody>
                  {% for todo in todo_list %}
                  <tr class="table-dark">
                    <th scope="row">{{ todo.id }}</th>
                    <td>{{ todo.title }}</td>
                    <td>{{ todo.description }}</td>
                    <td>
                      <ul class="list-group">
                        {% if todo.complete == False %}
                          <li class="list-group-item list-group-item-dark">In progress</li>
                        {% else %}
                          <li class="list-group-item list-group-item-success completed">Completed</li>
                        {% endif %}
                      </ul>
                    </td>
                    <td>
                      <a class="btn btn-success" href="{{ url_for('todo.update', id=todo.id) }}">Update</a>
                      <a class="btn btn-danger ms-1" href="{{ url_for('todo.delete', id=todo.id) }}">Delete</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>

          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}