app/post/models.py
import enum
from app import db
from datetime import datetime
from app.category.models import Category

class PostTypes(enum.Enum):
    SPORT = 1
    NEWS = 2
    MEMES = 3
    PUBLICATION = 4
    OTHER = 5
    

class Post(db.Model):
    __tablename__ = "posts"
    
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    text = db.Column(db.String(750))
    image = db.Column(db.String(50), nullable=False, default="defaultPostImg.jpg")
    createdAt = db.Column(db.DateTime, default=datetime.utcnow)
    postType = db.Column(db.Enum(PostTypes), default="PUBLICATION")
    enabled = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    
    category_id = db.Column(db.Integer, db.ForeignKey('сategories.id', name="category"), nullable=True)
#    category = db.relationship('Category', backref=db.backref('posts', lazy=True))
    
    def __repr__(self):
        return f"id: {self.id} | title: {self.title} | createdAt: \
            {self.createdAt.strftime('%d-%m-%Y %H:%M:%S')}"
    
    
    
    

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileField, FileAllowed


class AddUpdatePostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired("This field is required")])
    text = TextAreaField("Post content")
    image = FileField('Add post image', validators=[FileAllowed(['jpg', 'png'])])
    postType = SelectField("Post type (select one)", choices=[
        ('PUBLICATION', "Publication"), ('NEWS', 'News'), ('MEMES', 'Memes'),
        ('SPORT', 'Sport'), ('OTHER', 'Other')
    ])
    submit = SubmitField("Create post")

app/post/__init__.py
from flask import Blueprint
from .models import Post

post = Blueprint("post", __name__, template_folder="templates/post", \
                static_folder='static',  static_url_path='/post')

app/post/views.py
from flask import render_template, redirect, url_for, flash, abort, request
from .handlers.post_img_handler import add_post_img
from flask_login import current_user
from .forms import AddUpdatePostForm
from .models import Post
from app import db
from . import post

@post.route("/posts")
def posts():
    page = request.args.get('page', 1, type = int)
    posts = Post.query.order_by(Post.createdAt.desc()).paginate(page = page, per_page = 2)
    
    return render_template('posts.html', posts=posts)
    

@post.route("/post/create", methods=["GET", "POST"])
def create():
    form = AddUpdatePostForm()
    if form.validate_on_submit():
        title = form.title.data
        text = form.text.data
        postType = form.postType.data
        userID = current_user.id
        
        if form.image.data:
            image = add_post_img(form.image.data)
            post = Post(title=title, text=text, image=image, user_id=userID, postType=postType)
        else:
            post = Post(title=title, text=text, user_id=userID, postType=postType)
        
        db.session.add(post)
        db.session.commit()
        flash("Created new post", "success")
        
        return redirect(url_for("post.posts"))
    return render_template("createPost.html", form=form)


@post.route("/post/<int:id>")
def postID(id):
    post = Post.query.filter_by(id=id).first_or_404()
    return render_template("post.html", post=post, current_user=current_user)


@post.route("/post/<int:id>/delete")
def delete(id):
    post = Post.query.filter_by(id=id).first_or_404()
    
    if post.author != current_user:
        pass

    db.session.delete(post)
    db.session.commit()
    flash("Post has been deleted", "success")
    return redirect(url_for('post.posts'))


@post.route("/post/<int:id>/update", methods=["GET", "POST"])
def update(id):
    post = Post.query.filter_by(id=id).first_or_404()
    
    if post.author != current_user:
        pass
    
    form = AddUpdatePostForm()
    
    if form.validate_on_submit():
        if form.image.data:
            image = add_post_img(form.image.data)
            post.image = image
        post.title = form.title.data
        post.text = form.text.data
        post.postType = form.postType.data
        db.session.commit()
        flash('Post Updated', "success")
        return redirect(url_for('post.posts'))
    elif request.method == "GET":
        form.title.data = post.title
        form.text.data = post.text
        form.postType.data = post.postType
        
    return render_template('editPost.html', form=form)
            
    
        

app/post/templates/post/createPost.html
{% from 'fieldMacro.html' import displayField %}
{% extends 'base.html' %}
{% block title %}Create Post{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center mt-30">Create new post</h2>
        <br>
        <div class="d-flex align-items-center justify-content-start">
            <div class="mt-3">
                <form method="POST" novalidate enctype="multipart/form-data">
                    {{ form.csrf_token }}
                    {{ displayField(form.title, "Post title") }}
                    {{ displayField(form.text, "") }}
                    {{ displayField(form.image, "") }}
                    {{ displayField(form.postType, "") }}
                    <br><br>
                    {{ form.submit(class="btn btn-primary width-100") }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}  

app/post/templates/post/editPost.html
{% from 'fieldMacro.html' import displayField %}
{% extends 'base.html' %}
{% block title %}Edit Post{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center mt-30">Edit post</h2>
        <br>
        <div class="d-flex align-items-center justify-content-start">
            <div class="mt-3">
                <form method="POST" novalidate enctype="multipart/form-data">
                    {{ form.csrf_token }}
                    {{ displayField(form.title, "Post title") }}
                    {{ displayField(form.text, "") }}
                    {{ displayField(form.image, "") }}
                    {{ displayField(form.postType, "") }}
                    <br><br>
                    {{ form.submit(class="btn btn-primary width-100", value='Update post') }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}  

app/post/templates/post/post.html
{% extends 'base.html' %}
{% block title %}Post{% endblock %}
{% block content %}
    <div class="container mt-50">
        <h1 class="text-center">{{ post.title }}</h1>
        <br>
        <h4>Written by: {{ post.author.username }}</h4>
        Published: <small>{{ post.createdAt.strftime('%d/%m/%Y') }}</small>
        <br><br>
        
        {% if post.author == current_user %}
            <a href="{{ url_for('post.update', id=post.id) }}" class="btn btn-success">Edit</a>
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Delete
            </button>
        {% endif %}

        <br><br><br>

        <img src="{{ url_for('post.static', filename='images/' + post.image) }}" alt="Photo" class="postPhoto-large">
        {{ post.text }}
        <br><br><br>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Post Deleting</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  Do u wanna delete post ?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-warning">Delete</a>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

app/post/templates/post/posts.html
{% extends 'base.html' %}
{% block title %}Posts{% endblock %}
{% block content %}
    <div class="container mt-30">
        <h1 class="text-center">List of posts</h1>
        <br>
        <div class="d-flex justify-content-end">
            <a href="{{ url_for('post.create') }}" class="btn btn-success">
                <i class="bi bi-file-earmark-plus-fill"></i>
            </a>
        </div>
        <br><br><br><br>
        {% for post in posts %}
            <div class="row">
                <div class="col-2">
                    <img src="{{ url_for('post.static', filename='images/' + post.image) }}" alt="Photo" class="postPhoto-small">
                </div>
                <div class="col-5">
                    <h4><a href="{{ url_for('post.postID', id=post.id) }}">{{ post.title }}</a></h4>
                </div>
                <div class="col-3">
                    <h6>{{ post.postType }}</h6>
                </div>
                <div class="col-2">
                    <h6>{{ post.createdAt.strftime('%d/%m/%Y %H:%M:%S') }}</h6>
                </div>
            </div>
            <hr>
        {% endfor %}
        <br>
        <nav aria-label=''>
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not posts.has_prev %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('post.posts', page=posts.prev_num) }}"><</a>
                </li>

                {% for page_num in posts.iter_pages()  %}
                    <li class="page-item {% if page_num == posts.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for('post.posts', page=page_num ) }}">{{page_num}}</a>
                    </li>
                {% endfor %}

                <li class="page-item {% if not posts.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('post.posts', page=posts.next_num) }}">></a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}